### ISSUE TITLE
Lv 1 Computer

### ISSUE THREAD

**Issue by wang-henry** [ectodrop/loop-game#24]

**Comment by ectodrop** [comment]
PC has 4 states
PC starts in the "Off" state
Interacting with the PC puts it in the "boot state" where it shows a loading bar
If the power is turned off then the PC should switch to the "crash" state and become unresponsive.
If loading bar finishes to the end then it should switch to a "success" screen, if the player interacts with the PC in this state they should gain knowledge of the password

once the player gains knowledge of the password, the next time they open the control panel login screen it should show the password at the bottom of the login screen that they can type into the input box.
