### ISSUE TITLE
Tutorial to teach player about time

### ISSUE THREAD

**Issue by ectodrop** [ectodrop/loop-game#73]

**Comment by ectodrop** [comment]
Tutorial 1
- When the player first enters the room the camera pans to a monitor on the wall and starts a dialogue box where jarvis tells the player to carefully observe what's happening in the room
- After 10 seconds the camera pans back to jarvis who asks when a specific event (lights flickering) happened during the past 10 seconds
- The player has to enter the correct answer
- If the player gets the answer wrong, jarvis tells the player to restart time and repeats what he said before
- There should be a prompt on the screen to tell the player how to restart time

**Comment by LycheeKingwyz** [comment]
done
